### ISSUE TITLE
Shader generation pipeline

### ISSUE THREAD

**Issue by Hamcha** [hoverguys/rehover#15]
Tevasm can generate an example shader, but it's completely missing a parser from an input format which hasn't even been decided yet.
Plus all this has to be integrated into the pipeline as a tool in the Cmake files (and assets)

## My proposal

Shader sources should be as close to the original C code as possible, maybe without allowing any special syntax (such as loops and other constructs), basically ending up with just a list of function calls (which should be super-easy to parse).

It's kind of stupid that we're writing C++ into files so we can not write C++ into the game files but it makes sense if the only reason we're doing all this is to make the shaders unloadable etc. (which is indeed why I did all this).

It makes it supereasy to just copypaste the code in other homebrews or even a javascript tev implementation if we end up doing the live preview tool in JS+WebGL.

Tagging for comment: @zeroZshadow

**Comment by zeroZshadow** [comment]
LGTM

**Comment by Hamcha** [comment]
Tevasm has been finalized in 1c79687 and integrated into the toolchain in cce2dfd
