### ISSUE TITLE
Scene system

### ISSUE THREAD

**Issue by Hamcha** [hoverguys/rehover#16]
We need some sort of scene system to manage game states and resources (load/unload as needed).

What do we want from it?

### Some things to deal with

 - We said no scene graph, should we at least have a list of elements? Kinda like Unity without the hierarchy
 - How are scene defined? File format w/ editor? What should the format be like?
 - Do we want to ever be able to do sub-scenes (scenes in scenes)? An example could be sharing a demo mode scene (like a race being done by CPUs) for both the attract mode and main menu

### My idea

The format for the scenes should be something like:
 - List of resources needed
 - List of entities
    - For each entity, all the components (with references to resources when needed)

This would mean that we need a custom format that can translate a specific code and data to, for example, the `Renderable` constructor

**Comment by zeroZshadow** [comment]
Implementation is made
